apiVersion: apps/v1
kind: Deployment
metadata:
  name: Heho-0716
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Heho-0716
  template:
    metadata:
      labels:
        app: Heho-0716
    spec:
      containers:
      - image: okteto.dev/Heho-0716:latest
        name: Heho-0716
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "dabc7a71-c798-4415-9c7c-38eea32a5353"
        - name: Vless_Path
          value: "/vl111"
        - name: Vmess_UUID
          value: "dabc7a71-c798-4415-9c7c-38eea32a5353"
        - name: Vmess_Path
          value: "/vm222"
        - name: Share_Path
          value: "/v2link"
